name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web and macOS.
version: 5.0.6

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth_platform_interface:
    path: ../facebook_auth_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
